steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/jk-repo/jk-ml-sales-prediction:$SHORT_SHA',
        '.'
      ]
    id: 'Build Docker image'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/jk-repo/jk-ml-sales-prediction:$SHORT_SHA'
      ]
    id: 'Push to Artifact Registry'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'jk-cloud-run-app',
        '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/jk-repo/jk-ml-sales-prediction:$SHORT_SHA',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-env-vars', 'VERSION=$SHORT_SHA'
      ]
    id: 'Deploy to Cloud Run'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'release-$SHORT_SHA'
      - '--delivery-pipeline=jk-ml-sales-prediction-pipeline'
      - '--region=us-central1'
      - '--images=jk-ml-sales-prediction=gcr.io/$PROJECT_ID/jk-ml-sales-prediction:$SHORT_SHA'
images:
  - 'gcr.io/$PROJECT_ID/jk-ml-sales-prediction:$SHORT_SHA'      

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _SERVICE_NAME: cloud-run-app

